from pydantic import BaseModel, Field
from typing import List, Optional, Literal

class Evidence(BaseModel):
    id: str
    description: str
    owner: Literal["prosecutor", "defense", "public"]
    is_revealed: bool = False

class Statement(BaseModel):
    id: str
    agent: Literal["prosecutor", "defense", "judge"]
    action: Literal["PLEA", "REVEAL_EVIDENCE", "ARGUE", "OBJECT", "CONCEDE", "CLOSE", "VERDICT"]
    text: str
    evidence_used: List[str] = Field(default_factory=list, description="List of evidence IDs used in this statement")
    linked_counter_id: Optional[str] = Field(None, description="ID of the opponent's statement this directly counters")
    raw_xml: str = Field(..., description="The raw XML generated by the agent")

class Case(BaseModel):
    case_id: str
    charge: str
    facts: str
    evidence_pool: List[Evidence]

class Transcript(BaseModel):
    case: Case
    statements: List[Statement] = Field(default_factory=list)
    winner: Optional[Literal["prosecutor", "defense", "tie"]] = None

    def get_statement(self, statement_id: str) -> Optional[Statement]:
        for s in self.statements:
            if s.id == statement_id:
                return s
        return None
